name: Release

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Clean Release Drafts
      uses: ./
      with:
        github_token: ${{ secrets.github_token }}
        mode: cleanReleaseDrafts
