name: Release

on: [push]

jobs:
  run:
    
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v1
    - name: Build Number Generator
      uses: einaregilsson/build-number@v2
      with:
        token: ${{ secrets.github_token }}
    - name: Download Release Asset
      uses: ./
      with:
        github_token: ${{ secrets.github_token }}
        mode: downloadReleaseAsset
        tag: test-release
        filePath: ./hammer.png
        assetName: hammer_1f528.png
